name = "attention"
main = "worker.js"
compatibility_date = "2026-03-19"
workers_dev = false
keep_vars = true
placement = { mode = "smart" }

[vars]
VAPID_PUBLIC_KEY = "BJOm2JBG6kQe5CGPhT-SDrv6VpzdtwCANzJKvRZBBawY8eJ0rxeKtftDGNZS6BdCrjDzqZ0PpE-CMkp9SjNnwDs"
QWEATHER_LOCATION = "101280610"

[secrets]
required = [
  "QWEATHER_PRIVATE_KEY",
  "SEND_API_KEY",
  "SUBS_ENC_KEY",
  "VAPID_PRIVATE_KEY"
]

[assets]
directory = "./assets"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[[kv_namespaces]]
binding = "SUBS"
id = "c659f42d555b4a4ca17c7653677e64cc"

[triggers]
crons = ["0 */1 * * *", "15 0 * * *", "0 0,4,8,12 * * *"]

[[routes]]
pattern = "attention.debeetle.cn.eu.org"
zone_name = "debeetle.cn.eu.org"
custom_domain = true
